version: '3'
services:
  redis:
    image: 'redis:latest'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  redis-data: